#+PROPERTY: header-args :tangle yes

* Utilities and Functions
** Convert a table of package names and versions to a shell command argument
Such as for pip or apt

#+NAME: table-to-versioned-string
#+BEGIN_SRC elisp :var table=apt-sources package-manager="apt" :results silent
(defun table-to-versioned-string (table package-manager)
  ;; Joiner assigns whether we should use $package=$version or $package==$version
  (let ((joiner
         (cond ((string= package-manager "apt") "=")
               ((string= package-manager "pip") "=="))))
    (s-join " " (-map (lambda (row)
            (let ((package (car row))
                  (version (format "%s" (cadr row))))
              (if (string= "" version)
                  package
                (s-concat package joiner version))))
          table))))

(message (table-to-versioned-string table package-manager))
#+END_SRC

* Packages
Run all as root.
** Apt

*** Installs
Trying to sort these in terms of 'emergency' criticality. Very mission critical things at the top. Deps at the bottom.
#+NAME: apt-sources
| name             | version | comment                           |
|------------------+---------+-----------------------------------|
| curl             |         |                                   |
| gawk             |         | gnu awk, cause it's better        |
| sqlite3          |         |                                   |
| nmap             |         |                                   |
| wget             |         |                                   |
| xclip            |         |                                   |
| pass             |         |                                   |
| openvpn          |         |                                   |
| calibre          |         |                                   |
| htop             |         |                                   |
| jq               |         | Just critical                     |
| clang            |         | Used for Rust interop             |
| libnotify-bin    |         | Sending alerts to the desktop     |
| w3m              |         | Internet browsing stuff           |
| racket           |         |                                   |
| hunspell         |         |                                   |
| hunspell-en-us   |         |                                   |
| golang           |         | so hot right now                  |
<<<<<<< HEAD
| gnutls-bin       |         | For Emacs Circe                   |
=======
| fzf              |         | fuzzy searching                   |
>>>>>>> 12d78f5bf9ae8824336d1cfff21efd20461881f9
| transmission     |         |                                   |
| tidy             |         | html formatting                   |
| mplayer          |         | nice sound playing                |
| paperkey         |         | backing up /restoring GPG keys    |
| cmake            |         | requires ubuntu 19+, for libvterm |
| libtool-bin      |         | for libvterm                      |
| fonts-firacode   |         | for doom emacs                    |
| zlib1g-dev       |         | for installing python w/ pyenv    |
| build-essential  |         | python + pyenv                    |
| libssl-dev       |         | python + pyenv                    |
| libbz2-dev       |         | python + pyenv                    |
| libreadline-dev  |         | python + pyenv                    |
| libsqlite3-dev   |         | python + pyenv                    |
| llvm             |         | python + pyenv                    |
| libncurses5-dev  |         | python + pyenv                    |
| libncursesw5-dev |         | python + pyenv                    |
| xz-utils         |         | python + pyenv                    |
| tk-dev           |         | python + pyenv                    |
| libffi-dev       |         | python + pyenv                    |
| liblzma-dev      |         | python + pyenv                    |
| python-openssl   |         | python + pyenv                    |

#+NAME: INSTALLATION
#+HEADER: :var vstring=table-to-versioned-string(table=apt-sources, package-manager="pip")
#+HEADER: :dir "/sudo::/"
#+HEADER: :results raw
#+BEGIN_SRC shell
# I could do this more nicely and cleanly with the Python API, but I prefer to
# be able to do this without dependencies-- this should work on a fresh ubuntu
# install.
apt-get install -y $(echo $vstring)
#+END_SRC


* Shell
#+BEGIN_SRC shell
# NOTE You probably want to generate an SSH key for bitbucket for this machine.
git clone https://bitbucket.org/txru/passwords.git ~/.password-store
# NOTE You should fetch your GPG key yourself.
git clone https://bitbucket.org/txru/dotfiles.git ~/.dotfiles
python3 ~/.dotfiles/home/copier.py
#+END_SRC
* Emacs
#+BEGIN_SRC shell
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
yes | ~/.emacs.d/bin/doom install

mkdir -p ~/.emacs.d/.local/straight/repos/emacs-libvterm/build
cd ~/.emacs.d/.local/straight/repos/emacs-libvterm/build
cmake ..
make
cd -
#+END_SRC
#+END_SRC
* Python

** Create env
#+BEGIN_SRC elisp  :var location=(getenv "HOME")
(let* ((commands (list
                 (format "git clone https://github.com/pyenv/pyenv.git %s/.pyenv" location)
                 (format "git clone https://github.com/momo-lab/xxenv-latest.git %s/plugins/xxenv-latest"
                         (s-concat location "/.pyenv")
                 "pyenv latest install"
                 "pyenv global $(pyenv versions | tail -n 1)"
                 "mkdir -p $HOME/.zfunc")))
  (-map (lambda (command)
          (kev-command command))
        commands))
#+END_SRC
#+RESULTS:
| git clone https://github.com/pyenv/pyenv.git ~/.pyenv | 128 | fatal: destination path '/home/kev/.pyenv' already exists and is not an empty directory. |
| pyenv latest install                                  |   1 | Latest version is '3.8.2'                                                                |

** Install Libraries
#+NAME: general-purpose-python
| name                          | version | comment               |
|-------------------------------+---------+-----------------------|
| jupyter                       |   1.0.0 | science notebook      |
| black                         | 19.10b0 | formatting            |
| pyflakes                      |   2.2.0 | import optimization   |
| isort                         |  4.3.21 | sort imports          |
| mypy                          |   0.770 | typing                |
| 'python-language-server[all]' |  0.31.9 | LSP                   |
| pyls-mypy                     |   0.1.8 |                       |
| pyls-isort                    |   0.1.1 | isort                 |
| jedi                          |  0.17.0 | emacs python stuff    |
| ipython                       |  7.14.0 | repl                  |
| poetry                        |   1.0.5 | dependency management |
| virtualenv                    | 20.0.15 | envs                  |

#+BEGIN_SRC elisp :var table=general-purpose-python
(let* ((libraries (-map
                   (lambda (row)
                     (let ((package (car row))
                           (version (cadr row)))
                       (s-concat
                        package
                        (if (not (string= "" version))
                            (s-concat "==" version)
                          version))))
                   table)))
       (-map (lambda (lib)
               (kev-command (format "pip install --user %s" lib)))
             libraries))

#+END_SRC

#+RESULTS:




* Dotfiles
#+NAME: dotfiles
| filename                  | file_location                            | comment |
|---------------------------+------------------------------------------+---------|
| ssh_config                | ~/.ssh/config                            |         |
| gitconfig                 | ~/.gitconfig                             |         |
| gitignore                 | ~/.gitignore                             |         |
| pip.conf                  | ~/.pip/pip.conf                          |         |
| kdewalletrc               | ~/.config/kdewalletrc                    |         |
| redshift.conf             | ~/.config/redshift.conf                  |         |
| flake8                    | ~/.config/flake8                         |         |
| rustfmt.toml              | ~/.config/rustfmt/rustfmt.toml           |         |
| zshenv                    | ~/.zshenv                                |         |
| zshrc                     | ~/.zshrc                                 |         |
| profile                   | ~/.profile                               |         |
| fish/config.fish          | ~/.config/fish/config.fish               |         |
| zprofile                  | ~/.zprofile                              |         |
| systemd/emacs.service     | ~/.config/systemd/user/emacs.service     |         |
| systemd/gitwatch@.service | ~/.config/systemd/user/gitwatch@.service |         |

#+BEGIN_SRC python :var table=dotfiles :tangle "copier.py"
from pathlib import Path

home = Path.home()
dotfiles_path = home / "dotfiles" / "home"


def firefox_settings():
    import configparser

    firefox_ini = str(home / ".mozilla" / "firefox" / "profiles.ini")

    profiles = configparser.ConfigParser()
    profiles.read(firefox_ini)

    firefox_profile_paths = []
    for k, v in profiles.items():
        if "Profile" in k:
            firefox_profile_paths.append(v.get("Path"))

    for profile_key, profile in profiles.items():
        if "Profile" in profile_key:
            firefox_profile = (
                home / ".mozilla" / "firefox" / profile.get("Path") / "chrome"
            )
            firefox_profile.mkdir(parents=True, exist_ok=True)

            try:
                (firefox_profile / "userChrome.css").symlink_to(
                    dotfiles_path / "browser" / "userChrome.css"
                )
            except FileExistsError:
                pass

            print(f"Copied Firefox profile {profile.get('Path')}")

firefox_settings()

file_mappings = {(dotfiles_path / row[0]): Path(row[1]).expanduser() for row in table }

for source, target in file_mappings.items():
    print(target)
    try:
        try:
            target.unlink()
        except:
            pass
        target.parent.mkdir(parents=True, exist_ok=True)
        target.symlink_to(source)
    except Exception as exc:
        print(exc)

for func in (dotfiles_path / "fish/functions").glob("*"):
    target = home / ".config/fish/functions" / func.name
    try:
        target.unlink()
    except:
        pass
    target.parent.mkdir(parents=True, exist_ok=True)
    target.symlink_to(func)

#+END_SRC

#+RESULTS:
: None

* Config
* Scripts
** Remarkable lines file to SVG
#+BEGIN_SRC python :var dotfiles_dir=(s-concat (getenv "HOME") "/.dotfiles/home")
import os
import requests

outfile = os.path.expanduser("~/.dotfiles/home/scripts/rm2svg")

url = "https://github.com/reHackable/maxio/raw/master/tools/rM2svg"
response = requests.get(url).text

try:
    with open(outfile, "w") as f:
        f.write(response)
except Exception as e:
    print(e)
#+END_SRC

#+RESULTS:
: None
