#!/bin/zsh

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=1000
setopt SHARE_HISTORY

export BASE_PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/games

export BOOT_CLOJURE_VERSION=1.10.1

export BROWSER=/usr/bin/firefox
export EDITOR="/usr/bin/emacsclient -t"
export HISTFILE=.zhistory

export LOCAL_BIN=$HOME/.local/bin
export DOTFILES_DIR=$HOME/.dotfiles/home
export SNAP=/snap/bin

export GOPATH=$HOME/.go
export RUST_SRC_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export CARGO_BIN=$HOME/.cargo/bin
export NODENV=$HOME/.nodenv/bin
export PYENV=$HOME/.pyenv/bin
export NODENV_ENTRYPOINTS=$HOME/.nodenv/shims
export PYENV_ENTRYPOINTS=$HOME/.pyenv/shims
export DOOM_BIN=$HOME/.emacs.d/bin

export PATH=$PYENV_ENTRYPOINTS:$NODENV_ENTRYPOINTS:$BASE_PATH:$LOCAL_BIN:$CARGO_BIN:$RUST_SRC_PATH:$SNAP:$GOPATH/bin:$DOOM_BIN:$PYENV:$NODENV

fc -p ~/.zsh_history
