#!/bin/fish

set PATH (getconf PATH)

set BROWSER /usr/bin/firefox
set EDITOR "/usr/bin/emacsclient -t"

set -gx JAVA_HOME /usr/lib/jvm/java-8-openjdk/jre
set -gx LOCAL_BIN $HOME/.local/bin
set -gx CONDA_BIN $HOME/.anaconda3/bin

set -gx RUST_SRC_PATH $HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
set -gx RUST_BIN $HOME/.cargo/bin
set -gx PATH $CONDA_BIN:$PATH:$JAVA_HOME:$LOCAL_BIN:$RUST_SRC_PATH:$RUST_BIN
