#!/bin/zsh

export BASE_PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/games

export BOOT_CLOJURE_VERSION=1.10.1

export BROWSER=/usr/bin/firefox
export EDITOR="/usr/bin/emacsclient -t"
export HISTFILE=.zhistory

export LOCAL_BIN=$HOME/.local/bin
export DOTFILES_DIR=$HOME/.dotfiles/home

export RUST_SRC_PATH=$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
export CARGO=$HOME/.cargo/bin
export NODE_SCRIPTS=$HOME/.nodenv/versions/$(cat $HOME/.nodenv/version)/bin

export PATH=$PYENV_BIN:$BASE_PATH:$JAVA_HOME:$LOCAL_BIN:$CARGO:$RUST_SRC_PATH:$NODENV:$NODE_SCRIPTS
