#!/bin/zsh

alias sa="sudo apt"
alias sai="sa install"
alias saud="sa update"
alias saug="sa upgrade"
alias sar="sa remove"
alias saa="sa autoremove"

alias et="emacsclient -t"
alias ec="emacsclient -c"

alias sz="source ~/.zshrc"
alias na="ls"
alias la="ls -lah"

alias zup="antibody bundle < ~/dotfiles/home/zsh_plugins.txt > ~/.zsh_plugins.sh"

# source ~/.zshenv

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source ~/.zsh_plugins.sh
# source <(antibody init)
