#!/bin/zsh

alias ase="apt search"
alias sa="sudo apt"
alias sai="sa install"
alias saud="sa update"
alias saug="sa upgrade"
alias sar="sa remove"
alias saa="sa autoremove"

alias et="emacsclient -t"
alias ec="nohup emacsclient -c &> /tmp/emacs.out &"

alias sz="source ~/.zshrc"
alias na="ls"
alias la="ls -lah"

alias zup="antibody bundle < ~/dotfiles/home/zsh_plugins.txt > ~/.zsh_plugins.sh"

alias vre="sudo systemctl restart openvpn-client@US_Seattle.service"
alias vsto="sudo systemctl stop openvpn-client@US_Seattle.service"
alias vsta="sudo systemctl start openvpn-client@US_Seattle.service"

alias sc="sudo systemctl"
alias scu="systemctl --user"
alias jc="journalctl -xe"

# source ~/.zshenv

# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

source ~/.zsh_plugins.sh
# source <(antibody init)
