#!/usr/bin/env zsh

source ~/.zshenv

alias ase="apt search"
alias sa="sudo apt"
alias sai="sa install"
alias saud="sa update"
alias saug="sa upgrade"
alias sar="sa remove"
alias saa="sa autoremove"

alias et="emacsclient -t"
alias ec="nohup emacsclient -c &> /tmp/emacs.out &"

alias bw="bitwise"

alias vc="mullvad connect"
alias vd="mullvad disconnect"

alias ppush="pass git push origin master"
alias ppull="pass git pull origin master"

alias sz="source ~/.zshrc"
alias se="source ~/.zshenv"
alias na="ls"
alias la="ls -lah"

alias zup="antibody bundle < $DOTFILES_DIR/zsh_plugins.txt > ~/.zsh_plugins.sh"

alias vre="sudo systemctl restart openvpn-client@US_Seattle.service"
alias vsto="sudo systemctl stop openvpn-client@US_Seattle.service"
alias vsta="sudo systemctl start openvpn-client@US_Seattle.service"

alias sc="sudo systemctl"
alias scu="systemctl --user"
alias jc="journalctl -xe"
alias cop="python3 $DOTFILES_DIR/copier.py"

alias remark="rsync -avzz --rsync-path=/opt/bin/rsync r:/home/root/.local/share/remarkable/xochitl ~/org/remarkable/"

fc -p ~/.zsh_history
source ~/.zshenv
source ~/.zsh_plugins.sh
fpath+=$HOME/.zfunc

eval "$($HOME/.pyenv/bin/pyenv init -)"
