#!/bin/zsh

export SHELL=/usr/bin/zsh

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=1000
setopt SHARE_HISTORY

export BASE_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

export BROWSER=/usr/bin/firefox
export EDITOR="/usr/local/bin/emacsclient -t"
export HISTFILE=.zhistory

export LOCAL_BIN=$HOME/.local/bin
export DOTFILES_DIR=$HOME/.dotfiles/home
export SNAP=/snap/bin

export DOOM_BIN=$HOME/.emacs.d/bin

# NODENV BIN really needs to be at the front, because the system node always fucks everything up.
export PATH=$HOME/.nix-profile/bin:$BASE_PATH

fc -p ~/.zsh_history
# . "$HOME/.cargo/env"
