#!/bin/zsh

export SHELL=/usr/bin/zsh

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=1000
setopt SHARE_HISTORY

export BASE_PATH=/usr/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/games

export BOOT_CLOJURE_VERSION=1.10.1

export BROWSER=/usr/bin/firefox
export EDITOR="/usr/local/bin/emacsclient -t"
export HISTFILE=.zhistory

export LOCAL_BIN=$HOME/.local/bin
export DOTFILES_DIR=$HOME/.dotfiles/home
export SNAP=/snap/bin

export GHC_BIN=$HOME/.ghcup/bin
export CABAL_BIN=$HOME/.cabal/bin
export GOPATH=$HOME/.go
export RUST_SRC_PATH=$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library
export CARGO_BIN=$HOME/.cargo/bin
export NODENV=$HOME/.nodenv/bin
export NODENV_SHIM=$HOME/.nodenv/shims
export PYENV=$HOME/.pyenv/bin
export PYENV_SHIM=$HOME/.pyenv/shims
export NODENV_ENTRYPOINTS=$HOME/.nodenv/shims
export NODENV_BIN=$HOME/.nodenv/versions/14.2.0/bin
export PYENV_ENTRYPOINTS=$HOME/.pyenv/shims
export DOOM_BIN=$HOME/.emacs.d/bin

# NODENV BIN really needs to be at the front, because the system node always fucks everything up.
export PATH=$NODENV_BIN:$BASE_PATH:$LOCAL_BIN:$CARGO_BIN:$SNAP:$GOPATH/bin:$DOOM_BIN:$PYENV:$NODENV:$PYENV_SHIM:$NODENV_SHIM:$GHC_BIN:$CABAL_BIN

fc -p ~/.zsh_history
. "$HOME/.cargo/env"
