#!/bin/sh
# /usr/bin/i3exit

# with openrc use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && logind=/usr/bin/systemctl || logind=loginctl
locker="/usr/bin/dm-tool lock"

case "$1" in
    lock)
        $locker
        ;;
    logout)
        i3-msg exit
        ;;
    suspend-then-hibernate)
        $locker && $logind suspend-then-hibernate
        ;;
    hibernate)
        $locker && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
