#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p -i "$@")

modifier="show"
if [[ "$password" == *"OTP"* ]]; then
	modifier="otp"
fi

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass $modifier -c "$password" 2>/dev/null
else
	pass $modifier "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
