if [ -z "$ZSH_AUTO_RAN_FISH" ] && [ -x /apollo/env/envImprovement/bin/fish ]; then
    export ZSH_AUTO_RAN_FISH=YES
    LD_LIBRARY_PATH=/apollo/env/envImprovement/lib exec /apollo/env/envImprovement/bin/fish
fi
