#!/bin/zsh

PROMPT='[local] %3~ %# '

BRAZIL_BIN="/apollo/env/SDETools/bin"


# export JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/bin
export JDK_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export NPM=$HOME/.nvm/versions/node/v8.16.0/bin
export LOCALBIN=$HOME/.local/bin
export NODEPATH=$HOME/.nvm/versions/node/v12.2.0/bin
export CARGOPATH=$HOME/.cargo/bin
export TOOLBOX=$HOME/.toolbox/bin
export PYENV=$HOME/.pyenv/bin
export LINUXBREW=/home/linuxbrew/.linuxbrew/bin
export GOPATH=$HOME/go
export SNAPPATH=/snap/bin

BASE_PATH=usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export PATH=$PATH:$GOBIN:$LOCALBIN:$CARGOPATH:$TOOLBOX:$PYENV:$LINUXBREW:$NPM:$GOPATH/bin:$SNAPPATH
