#!/bin/zsh

PROMPT='[local] %3~ %# '

BRAZIL_BIN="/apollo/env/SDETools/bin"

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# export JDK_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export RODAR=$HOME/.rodar/bin
export ENV_IMPROVEMENT=/apollo/env/envImprovement/bin
export LOCALBIN=$HOME/.local/bin
export NODEPATH=$HOME/.nvm/versions/node/v12.2.0/bin
export CARGOPATH=$HOME/.cargo/bin
export TOOLBOX=$HOME/.toolbox/bin
export PYENV=$HOME/.pyenv/bin
export LINUXBREW=/home/linuxbrew/.linuxbrew/bin
export SNAPPATH=/snap/bin

BASE_PATH=usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export PATH=$BASE_PATH:$LOCALBIN:$CARGOPATH:$TOOLBOX:$PYENV:$LINUXBREW:$SNAPPATH:$ENV_IMPROVEMENT:$RODAR

unset JAVA_HOME
