#!/bin/zsh

PROMPT='[local] %3~ %# '

BRAZIL_BIN="/apollo/env/SDETools/bin"

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# export JDK_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export RODAR=$HOME/.rodar/bin
export ENV_IMPROVEMENT=$HOME/EnvImprovement/src/EnvImprovementUbuntu/bin
export LOCALBIN=$HOME/.local/bin
export NODEPATH=$HOME/.nvm/versions/node/v12.2.0/bin
export CARGOPATH=$HOME/.cargo/bin
export TOOLBOX=$HOME/.toolbox/bin
export PYENV=$HOME/.pyenv/bin
export LINUXBREW=/home/linuxbrew/.linuxbrew/bin
export SNAPPATH=/snap/bin
export NODENV_HOME=$HOME/.nodenv/shims
export NODENV_PACKAGES=$HOME/.nodenv/versions/$(cat $HOME/.nodenv/version)/bin
export NINJA_UTILS=$HOME/EnvImprovement/src/NinjaUtilsClojure/bin

# Local projects
export sdet=/workspace/sde/src/SDEIntegrationTests
export sde=/workspace/sde/src/SellerDiscountsEvaluatorService
export rudra=/workspace/rudra/src/Rudra
export ocean=/workspace/ocean/src/Ocean
export odyssey=/workspace/odyssey/src/TheOdyssey

# Configuration flags
export PASSWORD_STORE_ENABLE_EXTENSIONS=true

BASE_PATH=usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export PATH=$BASE_PATH:$LOCALBIN:$CARGOPATH:$TOOLBOX:$PYENV:$LINUXBREW:$SNAPPATH:$ENV_IMPROVEMENT:$RODAR:$NODENV_HOME:$NODENV_PACKAGES:$NINJA_UTILS

unset JAVA_HOME
