#!/bin/zsh

# exec /usr/bin/fish

# Set up the prompt

source $HOME/.zprofile
# Load the oh-my-zsh's library.

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system

alias sag="sudo apt"
alias sagi="sag install"
alias sagu="sag update"
alias saga="sag autoremove"
alias sagr="sag remove"
alias acs="apt-cache search"
alias acm="apt-cache madison"
alias svba="source venv/bin/activate"
alias sz="source ~/dotfiles/work/copier.sh && source ~/.zshrc"

alias bb="brazil-build"
alias bre="brazil-runtime-exec"
alias brep="bre python bin/manage.py"
alias bwsm="brazil ws --sync --md"

alias la='ls -lAFh'   #long list,show almost all,show type,human readable
alias lr='ls -tRFh'   #sorted by date,recursive,show type,human readable
alias lt='ls -ltFh'   #long list,sorted by date,show type,human readable

alias mon='psql -h fba-analysis-monster.db.amazon.com -p 8192 -d monster -U fba_analysis'
alias monroot="psql -h fba-analysis.c5g1ihldokmx.us-east-1.redshift.amazonaws.com -p 8192 -d monster -U root"
alias monroot='psql -h fba-analysis.c5g1ihldokmx.us-east-1.redshift.amazonaws.com -p 8192 -d monster -U root'
alias gol='psql -h fba-analysis-goldman.db.amazon.com -p 8192 -d goldman -U root'
alias wells='psql -h fba-wells.c5g1ihldokmx.us-east-1.redshift.amazonaws.com -p 8192 -d wells -U root'
alias edae="emacs --daemon &> ~/.emacs.d/log/$(date '+%m-%d-%y').log & "
alias et="emacsclient -t"
alias vipy="$VIRTUAL_ENV/bin/ipython"

SOUND_FOLDER="$HOME/Music"
alias pat='(play $HOME/Music/right_answer.mp3 2> /dev/null &)'
alias poke='(play $HOME/Music/wrong_answer.mp3 2> /dev/null &)'

export NVM_DIR="/Users/kllyter/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. /Users/kllyter/.miniconda/etc/profile.d/conda.sh
