#!/bin/zsh

# exec /usr/bin/fish

# Set up the prompt

source $HOME/.zprofile
# Load the oh-my-zsh's library.

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system

alias sa="sudo apt"
alias sai="sag install"
alias saud="sa update"
alias saar="sa autoremove"
alias sar="sa remove"
alias ase="apt-cache search"
alias acm="apt-cache madison"

alias svba="source venv/bin/activate"
alias sf="~/dotfiles/work/copier.py; and source ~/.config/fish/config.fish"

alias sz="source ~/.zshrc"

alias sc="systemctl"
alias scu="systemctl --user"
alias jc="journalctl -xe"

alias bb="brazil-build"
alias bbr="bb release"
alias bre="brazil-runtime-exec"
alias bte="brazil-test-exec"
alias bwsm="brazil ws --sync --md"
alias bnu="brazil ws create --name"
alias bp="brazil ws use -p"
alias bv="brazil ws use -vs"
alias brc="brazil-recursive-command"

alias i=ipython
alias python=python3
alias pipi="pip3 install --user"

alias la="ls -lah"

# alias wb="nohup ~/.local/share/sql_workbench/sqlworkbench.sh &"
alias edae="emacs --daemon > ~/.emacs.d/log/'(date '+%m-%d-%y')'.log & "
alias et="emacsclient -t"
alias ec="nohup emacsclient -c &> /tmp/nohup_emacs.out &"
alias vipy="$VIRTUAL_ENV/bin/ipython"
alias d=ddgr
alias g=googler
alias python=python3
alias pip=$HOME/.pyenv/shims/pip3

alias ppush "pass git push origin master"
alias ppull "pass git pull --rebase origin master"

export NVM_DIR="/Users/kllyter/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(pyenv init -)"

function sync_dots() {
    rsync -a --cvs-exclude ~/dotfiles/ desk:~/dotfiles &
    # rsync -a --cvs-exclude ~/dotfiles/ d:~/dotfiles
    # rsync -a --cvs-exclude ~/dotfiles/ e:~/dotfiles
    rsync -a --cvs-exclude ~/dotfiles/ f:~/dotfiles &
}

fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

source /home/ANT.AMAZON.COM/kllyter/.config/broot/launcher/bash/br
